<h1>Apresentação</h1>

<?php
/* Lista de publicacoes */
echo '<h1>Lista da publicacoes indexadas</h1>';
echo $journals_list;


/* Historico */
$t = '
<h1>Histórico</h1>
A ideia para a criação de uma base de dados para estudo da produção em Ciência da Informação surgiu na concepção do projeto de pós-doutorado da professora Leilah Santiago Bufrem, em 1995, com o objetivo de desenvolver um repertório representativo da produção científica do Brasil e da Espanha. A partir da decisão institucional binacional, contou com a participação dos professores Elías Sanz Casado e José Antonio Moreiro González, da Universidad Carlos III de Madrid (UC3M), e da professora titular aposentada Wanda Maria Maia da Rocha Paranhos, do Departamento de Ciência e Gestão da Informação da Universidade Federal do Paraná (UFPR). 
Com a proposta concebida, a Base Brasil/Espanha de Artigos de Periódicos da área em Ciência da Informação (BRES) tornou-se objeto de estudo e fonte de pesquisas dos grupos coordenados pelos professores Elías Sanz Casado, da UC3M, e Leilah Santiago Bufrem, da UFPR. O propósito inicial dessa concepção era proporcionar ambiente tecnológico e operacional para a realização dos estudos comparativos entre a produção brasileira e espanhola. Estudos deste tipo vinham sendo realizados com dificuldades devido à falta de padronização e dificuldades de localizar repositórios específicos da área, uma vez que nem todos os periódicos estavam indexados nas bases de dados, e que desses, em geral, eram bases referenciais. 
A base então denominada Brasil Espanha (BRES) foi planejada em 1996, e, para sua concretização, foi adotado o software ProCite desenvolvido pelo Institute for Scientific Information (ISI) Research Soft. 
O ProCite, um software de gerenciamento de referências científicas, foi concebido nos anos de 1980, por Victor Rosenberg, professor associado da Faculdade de Biblioteconomia e Estudos de Informação da Universidade de Michigan. A primeira versão do ProCite foi disponibilizada em 1983 como um software para construção de uma bibliografia pessoal (Personal Bibliographic Software) (BIGGS, 1995). Em 1996, o ProCite foi comprado pelo Institute for Scientific Information, uma divisão da Thomson Reuters que o manteve até maio de 2013, quando foi substituído pelo EndNote.
A opção em utilizar o ProCite também se deu pelo fato de a Universidad Carlos III de Madrid já estar familiarizada com a ferramenta. O software permitia, além da criação de diversos bancos de dados, a criação de filtros, busca e recuperação da informação e a emissão de relatórios, possibilitando a exportação de dados para softwares como o Excel. O ProCite ajudava a controlar informações referenciais e, ainda, possibilitava a integração com o protocolo Z39.50 utilizado nas principais bibliotecas da Europa e dos Estados Unidos, para pesquisas.
A coleta de dados era essencialmente referencial, com indicação do título, autores, resumo, palavras-chave, localização física ou eletrônica e identificação da fonte publicadora, com o título do periódico, volume, fascículo e ano. As informações provinham dos dois países, sendo originárias de bases de dados online, CD-ROM, correio eletrônico, bibliotecas digitais e exemplares disponíveis nos acervos das bibliotecas.
Assim, embora o trabalho de criação e manutenção já houvesse iniciado, os procedimentos de pesquisa para a difusão de um repertório binacional se fortaleceram, quando concretizado por um projeto interinstitucional, favorecido por um convênio entre a Universidad Carlos III de Madrid (Espanha) e a Universidade Federal do Paraná (Brasil), em 2005. Justificou-se o convênio pelo fato de que Espanha e Brasil representavam dois países nos quais a produção de conhecimentos e a investigação na área apresentavam características e desenvolvimento relativamente equilibrados, com produção e regularidade semelhantes na atividade científica.
O convênio favoreceu a troca de informações e a mobilidade de professores e estudantes brasileiros para a Espanha, como de professores espanhóis para o Brasil. A ida de duas bolsistas de Iniciação Científica (IC), orientadas pela coordenadora do projeto (BUFREM, 2006), e a vinda dos professores Elias Sanz-Casado, José Antonio Moreiro González e José Antonio Frías são frutos deste convênio.
O processo inicial de investigação foi construído com base em duas vertentes: uma delas dirigida à literatura na área, voltada às tendências temáticas e suas raízes teóricas, cujos procedimentos integram estudos métricos com as análises de conteúdo e de domínio, especialmente focadas nos artigos de periódicos e comunicações em eventos; a outra vertente, voltada à comparação entre as tendências verificadas na literatura dos dois países participantes do convênio, incluiu em seu plano de trabalho atividades didáticas e de pesquisa, a partir dos questionamentos encontrados na literatura sobre a situação da CI diante das inovações e das transformações da contemporaneidade. 
As atividades relativas ao projeto inicial, portanto, inseridas em um contexto mais amplo de preocupações, partiam de questões levantadas sobre os conhecimentos e metodologias construídos interinstitucionalmente, de modo que se integrassem programas, conteúdos e práticas de pesquisa e ensino. 
A crença de que, ao oferecer condições para o reconhecimento e análise, a partir da literatura especializada, de expressões diferenciadas de práticas de investigação, se possa contribuir para a formalização de realizações concretas com o apoio de uma base de dados é o que motivou a continuidade desse trabalho coletivo, que passou a se direcionar apenas para uma base de caráter nacional. Assim, ao subsidiar com uma ferramenta dinâmica os alunos, professores, pesquisadores e profissionais em busca da melhoria na qualidade das publicações periódicas da área de CI, o Grupo E2PC contribuiu sobremodo para a socialização dos saberes no ensino superior, servindo como fonte de estudos e pesquisas, no Brasil e no exterior. 
Para o seu desenvolvimento, foram despendidos esforços de quase duas décadas de trabalho relativos à vertente operacional, a fim de manter sua atualização de novos artigos, e a vertente da pesquisa, que utiliza os dados para compreensão da CI no Brasil. As duas vertentes se complementam na continuidade a um processo mais amplo, que expressa a luta pela permanência de resultados, aqui considerados de valor universal. Com o apoio desse corpus unificador de saberes, têm sido realizados, pelos pesquisadores do país e do exterior, estudos analíticos e descritivos sobre a produção científica e editorial da área, mapeamentos relacionados a campos de pesquisa, enfoques metodológicos, estudos de autoria e de relações interinstitucionais. 
Destacam-se, nesse sentido, reflexões sobre as tendências mais recentes da área da CI expressas na literatura, as categorias que a representam de modo mais expressivo, as raízes teóricas dessas tendências, os autores mais representativos e suas origens. Também se destacam nessa busca os problemas concretos enfrentados pela área, as contradições que os mobilizam e sua presença em estudos de casos específicos. Para a escolha do enfoque e instrumental metodológico da pesquisa, os pesquisadores apoiaram-se em estudos bibliométricos e cientométricos que já vinham sendo realizados pelos grupos das universidades conveniadas e cujas contribuições à análise sobre características e comportamento de campos específicos do conhecimento têm seus resultados amplamente divulgados.
Os elementos introdutórios anteriormente analisados também servem para situar historicamente o produto concreto - a Base de Dados Referenciais de Artigos de Periódicos em Ciência da Informação (Brapci) - como aporte da área da informação para a produção de saberes no ensino superior, realizado graças a essa mobilização constante de esforços individuais em sonho coletivo. 
Esse produto passou a contar mais precisamente com a atuação da coordenadora do Projeto Brapci e do Grupo E2PC , e especialmente do Bolsista de Iniciação Científica (PIBIC/CNPq), Francisco Daniel de Oliveira Costa. Além dessas contribuições pessoais ao projeto, contou com a participação efetiva de todos os bolsistas de Iniciação Científica e membros do Grupo de Pesquisa E2PC. 
Desde a ideia inicial de reunir a literatura periódica da área de CI em repositório que facilitasse a busca e recuperação da informação para pesquisadores, acadêmicos e a comunidade em geral até os três primeiros anos da implantação do projeto (2000-2003), foram levantados e indexados os títulos de 13 periódicos da área e, paralelamente, realizada busca no acervo da Biblioteca do Setor de Ciências Sociais Aplicadas (BSCSA) da UFPR, onde foram verificados os periódicos do acervo físico relacionados à área de CI. Os fascículos não encontrados foram solicitados aos editores ou, após localização no Catálogo Coletivo Nacional de Publicações Seriadas (CCN), a outras bibliotecas, para que sejam preenchidos os dados de acordo com os campos definidos para a sua representação na base que inicialmente era desenvolvida no ProCite3.
Nos anos seguintes (2004-2008), foram realizadas análises específicas sobre as características temáticas, metodológicas e formais da literatura, obedecendo-se aos pressupostos iniciais e com a incorporação à base das publicações que atendiam a esses critérios. Essa análise possibilitou a ampliação significativa da quantidade de títulos selecionados; dos 13 iniciais para 27 títulos, até 2008, registrando-se 4.637 artigos publicados (BUFREM; PINTO, 2008).
Como forma de fortalecimento da estrutura de trabalho, foram apresentados e aprovados pelo CNPq, entre 2006 e 2008, dois projetos de Leilah Santiago Bufrem: o primeiro, intitulado Opções metodológicas em pesquisa: a contribuição da área da informação para a produção de saberes no Ensino Superior, relacionado ao processo 401981/2007-0 da linha de fomento “Apoio a Projetos de Pesquisa/Edital MCT/CNPq 50/2006 Ciências Humanas, Sociais e Sociais Aplicadas”; o segundo projeto, intitulado Metodologia para criação de uma base de dados online de acesso público: modelizando práticas para a socialização de saberes, culminou com a consolidação e disponibilização ao público da Brapci. Os projetos proporcionaram verbas para que se adquirisse material suficiente para a infraestrutura e o processo de implantação e manutenção da Brapci, apoiado também pelos bolsistas do PIBIC/CNPq.
Em 2007, começaram as primeiras experimentações na tentativa de converter a base de dados do ProCite para uma versão online acessível na Web. As primeiras tentativas foram realizadas pelo aluno de graduação, Francisco Daniel de Oliveira Costa, que realizava conversões periódicas da base original para a web. Dentro deste processo, o maior problema tinha origem na base do ProCite, por ser monousuária, ou seja, somente uma pessoa poderia trabalhar com a versão vigente da base para alimentá-la com novos registros, o que ocasionava, algumas vezes, versões diferentes do original e perda de trabalho quando alimentado na versão incorreta.
Em 2009, incorporaram-se mais três títulos de publicações à Brapci e foi implantado o mecanismo de coleta automática de registros, utilizando-se o protocolo OAI-PMH de arquivos abertos. Esta ferramenta de coleta, desenvolvida por Rene Faustino Gabriel Junior, possibilitou varreduras periódicas das publicações, coletando artigos novos, sem a necessidade de coleta manual. Isso possibilitou um crescimento significativo da base em quase dois mil registros adicionais, na época, graças ao acesso em ambiente virtual de edições antes não acessíveis, as quais foram identificadas e incorporadas por meio de trocas de metadados. Até outubro do ano de 2009, a Brapci havia reunido referências de 30 publicações periódicas vigentes e históricas produzidas no Brasil, concentrando 6.167 artigos em CI, o que proporcionou aos pesquisadores mapeamentos relacionados a áreas temáticas, enfoques e autoria a partir desse corpus.
Pela volatilidade dos links dos periódicos e pela constante troca de endereços virtuais, a coordenação da Brapci em conjunto com o Grupo E2PC decidiu realizar a coleta não somente dos metadados, mas a incorporação dos artigos na íntegra com os PDFs, transformando a Brapci não somente em uma base de referência, mas em repositório da CI. Por questões de direitos autorais, só são disponibilizados os arquivos que atendem à política de acesso aberto, Creative Commons, ou que tenha autorização dos editores ou representantes legais da publicação.
Dentro das políticas de indexação, a coordenação optou por não criar barreiras de indexação, sendo critério <i>sine qua non</i> que o periódico tenha como tema assuntos relativos à Ciência da Informação.
Assim, foi sendo desenvolvida e consolidada a Brapci, cujos critérios de construção, manutenção e abrangência a habilitam como única no Brasil com o potencial de recuperação explicitado para análise diacrônica, relevância que sobreleva no processo de produção e disseminação do conhecimento, tanto na CI como em campos correlatos, dadas as características interdisciplinares da área.
Atualmente, a Brapci disponibiliza 37 publicações indexadas da área, sendo 29 títulos científicos vigentes e 8 que já cessaram suas publicações, compondo 954 fascículos, com 8.772 artigos, 53.154 citações (referências) disponibilizadas no período de 1972 a 2014. Apresenta três módulos na sua configuração: o módulo público, para consultas rápidas; o módulo de manutenção, para revisão e correções da base; e o módulo pesquisador, para análises bibliométricas. Para o público, é disponibilizada uma nuvem de tags como interface visual, para guiar o usuário, sugerindo termos de busca e recuperação. A nuvem é composta pelas etiquetas mais consultadas, isto é, o tamanho da fonte das tags representa proporcionalmente a quantidade de utilizações da etiqueta nas buscas dos usuários.
Com essas características, a Brapci é uma base de dados cujas condições de efetivação de pesquisas a situam como paradigmática, graças ao desenvolvimento do seu modelo, marcado pelo contínuo aperfeiçoamento na sistematização e organização da literatura periódica da área, em prol da localização e obtenção de artigos de periódicos científicos da área de Ciência da Informação (CI), oferecendo suporte à pesquisa, à organização e à análise de dados. Além disso, tem subsidiado estudos na busca da melhoria na qualidade das publicações periódicas da área de Ciência da Informação e correlatas, contribuindo para socializar saberes editoriais. No sentido de dar continuidade a este trabalho, atualmente estão sendo discutidas possibilidades de parceria com outras bases, com o intuito de incorporar outras modalidades bibliográficas, como teses e dissertações, livros e eventos da área. (BUFREM; et al., 2010)
';

/* prepara texto para impressão */
$t = troca($t,chr(13),'£');
$t = troca($t,chr(10),'');
$tt = splitx('£',$t);
echo '<div class="texto">';
for ($r=0;$r < count($tt);$r++)
	{
		echo '<p>'.substr($tt[$r],1,strlen($tt[$r])).'</p>';
	}
echo '</div>';

