# Generated by Django 2.0.4 on 2018-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='jnl_active',
            field=models.IntegerField(default=1, verbose_name='Active'),
        ),
    ]
