# Generated by Django 2.0.4 on 2018-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0002_sources_jnl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='jnl_ano_final',
            field=models.CharField(max_length=6, verbose_name='Fim da publicação'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_ano_inicio',
            field=models.CharField(max_length=6, verbose_name='Início da publicação'),
        ),
    ]
