# Generated by Django 2.0.4 on 2018-05-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0003_auto_20180501_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sources',
        ),
    ]
