<?
require("cab.php");
?>
<h1>IV Encontro Brasileiro de Bibliometria e Cientometria (EBBC)</h1>
<P>A Bibliometria e a Cientometria têm na informação científica e tecnológica seus principais objetos de investigação, configurando-se como campos científicos relativamente novos. Internacionalmente elas já se encontram mais organizadas desde os anos 60 e 70. No Brasil os estudos iniciaram na década de 70.</P>
<P>O processo de consolidação tem sido conduzido por pesquisadores da Ciência da Informação e também de outras áreas. Essa característica multidisciplinar ficou evidenciada na primeira e na segunda edição do Encontro Brasileiro de Bibliometria e Cientometria, realizadas no Rio de Janeiro e em São Carlos - SP, em 2008 e 2010, respectivamente, quando participaram pesquisadores de diferentes áreas da ciência que desenvolvem pesquisa sobre o tema.</P>
<P>Devido a uma demanda crescente pela temática, buscou-se dar continuidade aos estudos nesse campo de conhecimento, então, em 2012, na cidade de Gramado(RS), os estudos se aprofundaram em busca de uma maior compreensão d as nuances e da diversidade das áreas de Bibliometria e Cientometria no intuito de unificar os esforços e consolidar a identidade acadêmico-científica no país. O III EBBC marca definitivamente a força do evento, com um público médio de 170 pessoas, obteve 115 trabalhos submetidos de pesquisadores de todo o país e até de outras nações.</P>
<P>Nas três edições do EBBC foram abordados assuntos como: aspectos teóricos e metodológicos; caráter multidisciplinar dos estudos cientométricos; indicadores bibliométricos e cientométricos para a política e gestão de CT&I; interface com a sociologia e a história da ciência; redes sociais e bibliometria.</P>
<P>Após esses encontros, a comunidade científica da área percebeu uma maior interação e mobilização entre os estudiosos e grupos de pesquisa. Notadamente os EBBCs proporcionaram um maior diálogo entre os pesquisadores, aprofundar a discussão de assuntos relacionados à ciência brasileira e aperfeiçoaram os métodos e técnicas aplicados à área.</P>
<P>Assim, o 4º Encontro Brasileiro de Bibliometria e Cientometria surge como um marco na solidificação de um desejo coletivo de pesquisadores em constituir uma massa crítica voltada aos estudos da Bibliometria e Cientometria,e, além disso, buscar parcerias nos diversos espaços sociais das quais se acredita ser importante a penetração e contribuição dos progressos sobre o tema. O evento será realizado no período de 14 a 16 de maio de 2014, em Recife - PE</P>	

<? require("foot.php");?>
