# Generated by Django 2.0.4 on 2018-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_active',
            field=models.IntegerField(default=1, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_ano_final',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Fim da publicação'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_ano_inicio',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Início da publicação'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_cidade',
            field=models.IntegerField(null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_collection',
            field=models.CharField(max_length=5, null=True, verbose_name='Coleção'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_issn_eletronico',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='eISSN'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_issn_impresso',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da fonte'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_name_abrev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da fonte'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_oai_from',
            field=models.CharField(max_length=5, null=True, verbose_name='Ano de coleta'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_oai_token',
            field=models.CharField(max_length=5, null=True, verbose_name='Ano de coleta'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_periodicidade',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_scielo',
            field=models.IntegerField(null=True, verbose_name='Scielo'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_url',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='jnl_url_oai',
            field=models.SlugField(blank=True, null=True, verbose_name='URL OAI-PMH'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update at'),
        ),
    ]
