# Generated by Django 2.0.4 on 2018-05-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20180501_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sources',
            new_name='Source',
        ),
    ]
