# Generated by Django 2.0.4 on 2018-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20180505_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='jnl_cidade',
            field=models.IntegerField(default=0, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='source',
            name='jnl_scielo',
            field=models.IntegerField(default=0, verbose_name='Scielo'),
        ),
    ]
