# Generated by Django 2.0.4 on 2018-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_auto_20180505_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRecords',
            fields=[
                ('id_lr', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_identifier', models.CharField(blank=True, max_length=100, verbose_name='Identifier')),
                ('lr_datestamp', models.DateTimeField(verbose_name='datestamp')),
                ('lr_setSpec', models.DateTimeField(blank=True, max_length=20, verbose_name='setSpec')),
                ('lr_status', models.DateTimeField(blank=True, max_length=20, verbose_name='status')),
            ],
        ),
    ]
