# Generated by Django 2.0.4 on 2018-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_listrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrecords',
            name='lr_jnl',
            field=models.IntegerField(default=0, verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='listrecords',
            name='lr_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='status'),
        ),
    ]
