# Generated by Django 2.0.4 on 2018-05-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_identify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identify',
        ),
    ]
