# Generated by Django 2.0.4 on 2018-05-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_delete_identify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id_i', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('i_repositoryName', models.CharField(max_length=100, verbose_name='RepositoryName')),
            ],
        ),
    ]
