# Generated by Django 2.0.4 on 2018-05-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_identify'),
    ]

    operations = [
        migrations.AddField(
            model_name='identify',
            name='adminEmail',
            field=models.CharField(max_length=100, null=True, verbose_name='adminEmail'),
        ),
        migrations.AddField(
            model_name='identify',
            name='baseURL',
            field=models.CharField(max_length=100, null=True, verbose_name='baseURL'),
        ),
        migrations.AddField(
            model_name='identify',
            name='compression',
            field=models.CharField(max_length=20, null=True, verbose_name='compression'),
        ),
        migrations.AddField(
            model_name='identify',
            name='deletedRecord',
            field=models.CharField(max_length=20, null=True, verbose_name='deletedRecord'),
        ),
        migrations.AddField(
            model_name='identify',
            name='granularity',
            field=models.CharField(max_length=20, null=True, verbose_name='granularity'),
        ),
        migrations.AddField(
            model_name='identify',
            name='protocolVersion',
            field=models.CharField(max_length=5, null=True, verbose_name='protocolVersion'),
        ),
        migrations.AddField(
            model_name='identify',
            name='repositoryName',
            field=models.CharField(max_length=100, null=True, verbose_name='RepositoryName2'),
        ),
        migrations.AlterField(
            model_name='identify',
            name='i_repositoryName',
            field=models.CharField(max_length=100, null=True, verbose_name='RepositoryName'),
        ),
    ]
