# Generated by Django 2.0.4 on 2018-05-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_auto_20180505_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identify',
            name='i_repositoryName',
        ),
    ]
