# Generated by Django 2.0.4 on 2018-05-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_identify_jnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='identify',
            name='earliestDatestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Update at'),
        ),
    ]
