# Generated by Django 2.0.4 on 2018-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id_geo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('geo_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Local')),
                ('geo_countryCode', models.CharField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('geo_lat', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Lat.')),
                ('geo_lng', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Log.')),
                ('geo_adminName1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Juridisção 1')),
                ('geo_adminCode2', models.IntegerField(blank=True, default=0, null=True, verbose_name='JurCod2')),
                ('geo_adminName2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Juridisção 2')),
                ('geo_adminCode3', models.IntegerField(blank=True, default=0, null=True, verbose_name='JurCod3')),
                ('geo_adminName3', models.CharField(blank=True, max_length=40, null=True, verbose_name='Juridisção 3')),
            ],
        ),
    ]
