# Generated by Django 2.0.4 on 2018-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0002_auto_20180505_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geo_adminCode1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='JurCod1'),
        ),
    ]
