# Generated by Django 2.0.4 on 2018-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0003_place_geo_admincode1'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geo_uri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='URI'),
        ),
    ]
